pokemon_moves_dict = {
    "Normal": {
        "Physical": [
            # {"ID": 0, "Move": "Nothing", "Power": 0},
            {"ID": 9, "Move": "Thrash", "Power": 18},
            {"ID": 18, "Move": "Cut", "Power": 10},
            {"ID": 20, "Move": "Super Fang", "Power": 0},
            {"ID": 39, "Move": "Double Slap", "Power": 4},
            {"ID": 48, "Move": "Return", "Power": 0},
            {"ID": 50, "Move": "Strength", "Power": 0},
            {"ID": 61, "Move": "Bide", "Power": 0},
            {"ID": 66, "Move": "Endeavor", "Power": 0},
            {"ID": 67, "Move": "Facade", "Power": 14},
            {"ID": 71, "Move": "Constrict", "Power": 2},
            {"ID": 78, "Move": "Smelling Salts", "Power": 12},
            {"ID": 81, "Move": "Slash", "Power": 14},
            {"ID": 96, "Move": "Rapid Spin", "Power": 4},
            {"ID": 121, "Move": "Flail", "Power": 2},
            {"ID": 123, "Move": "Self Destruct", "Power": 0},
            {"ID": 125, "Move": "Bind", "Power": 4},
            {"ID": 132, "Move": "Extreme Speed", "Power": 16},
            {"ID": 139, "Move": "Headbutt", "Power": 6},
            {"ID": 140, "Move": "Double Edge", "Power": 20},
            {"ID": 154, "Move": "Tackle", "Power": 6},
            {"ID": 155, "Move": "Explosion", "Power": 0},
            {"ID": 161, "Move": "Slam", "Power": 16},
            {"ID": 166, "Move": "Egg Bomb", "Power": 10},
            {"ID": 168, "Move": "Barrage", "Power": 1},
            {"ID": 176, "Move": "Horn Attack", "Power": 8},
            {"ID": 177, "Move": "Horn Drill", "Power": 0},
            {"ID": 190, "Move": "Quick Attack", "Power": 4},
            {"ID": 201, "Move": "Spike Cannon", "Power": 3},
            {"ID": 203, "Move": "Take Down", "Power": 8},
            {"ID": 226, "Move": "Fake Out", "Power": 8},
            {"ID": 228, "Move": "Pay Day", "Power": 8},
            {"ID": 235, "Move": "Body Slam", "Power": 12},
            {"ID": 247, "Move": "Guillotine", "Power": 0},
            {"ID": 248, "Move": "Vice Grip", "Power": 6},
            {"ID": 250, "Move": "Pound", "Power": 6},
            {"ID": 260, "Move": "Scratch", "Power": 6},
            {"ID": 261, "Move": "Hyper Fang", "Power": 16},
            {"ID": 263, "Move": "Secret Power", "Power": 14},
            {"ID": 264, "Move": "Dizzy Punch", "Power": 6},
            {"ID": 271, "Move": "Stomp", "Power": 12},
            {"ID": 275, "Move": "Crush Claw", "Power": 14},
            {"ID": 277, "Move": "Present", "Power": 0},
            {"ID": 287, "Move": "Covet", "Power": 8},
            {"ID": 294, "Move": "Wrap", "Power": 0},
            {"ID": 311, "Move": "Fury Attack", "Power": 1},
            {"ID": 312, "Move": "Fury Swipes", "Power": 5},
            {"ID": 314, "Move": "False Swipe", "Power": 40},
            {"ID": 321, "Move": "Mega Kick", "Power": 16},
            {"ID": 322, "Move": "Mega Punch", "Power": 16},
            {"ID": 328, "Move": "Frustration", "Power": 0},
            {"ID": 347, "Move": "Comet Punch", "Power": 3},
            {"ID": 348, "Move": "Skull Bash", "Power": 10},
            # {"ID": 352, "Move": "Struggle", "Power": 30},
            {"ID": 357, "Move": "Bide", "Power": 2},
            {"ID": 455, "Move": "Giga Impact", "Power": 60},
            {"ID": 471, "Move": "Natural Gift", "Power": 1},
            {"ID": 487, "Move": "Double Hit", "Power": 3},
            {"ID": 497, "Move": "Last Resort", "Power": 30},
            {"ID": 505, "Move": "Crush Grip", "Power": 15},
            {"ID": 516, "Move": "Feint", "Power": 5},
            {"ID": 541, "Move": "Rock Climb", "Power": 12},
        ],
        "Special": [
            {"ID": 25, "Move": "Snore", "Power": 4},
            {"ID": 31, "Move": "Weather Ball", "Power": 5},
            {"ID": 60, "Move": "Razor Wind", "Power": 16},
            {"ID": 145, "Move": "Swift", "Power": 10},
            {"ID": 152, "Move": "Sonic Boom", "Power": 0},
            {"ID": 207, "Move": "Tri Attack", "Power": 6},
            {"ID": 241, "Move": "Hyper Voice", "Power": 18},
            {"ID": 242, "Move": "Hyper Beam", "Power": 30},
            {"ID": 245, "Move": "Spit Up", "Power": 20},
            {"ID": 457, "Move": "Trump Card", "Power": 1},
            # {"ID": 467, "Move": "Judgment", "Power": 20},
            {"ID": 474, "Move": "Wring Out", "Power": 1},
        ],
        "Status": [
            {"ID": 3, "Move": "Yawn", "Power": 0},
            {"ID": 4, "Move": "Lovely Kiss", "Power": 0},
            {"ID": 6, "Move": "Morning Sun", "Power": 0},
            {"ID": 10, "Move": "Sweet Scent", "Power": 0},
            {"ID": 11, "Move": "Charm", "Power": 0},
            {"ID": 17, "Move": "Encore", "Power": 0},
            {"ID": 19, "Move": "Rage", "Power": 0},
            {"ID": 21, "Move": "Pain Split", "Power": 0},
            {"ID": 24, "Move": "Swagger", "Power": 0},
            {"ID": 26, "Move": "Heal Bell", "Power": 0},
            {"ID": 27, "Move": "Screech", "Power": 0},
            {"ID": 34, "Move": "Sing", "Power": 0},
            {"ID": 37, "Move": "Smokescreen", "Power": 0},
            {"ID": 54, "Move": "Odor Sleuth", "Power": 0},
            {"ID": 55, "Move": "Sharpen", "Power": 0},
            {"ID": 56, "Move": "Double Team", "Power": 0},
            {"ID": 58, "Move": "Harden", "Power": 0},
            {"ID": 59, "Move": "Disable", "Power": 0},
            {"ID": 74, "Move": "Focus Energy", "Power": 0},
            {"ID": 85, "Move": "Tickle", "Power": 0},
            {"ID": 89, "Move": "Mean Look", "Power": 0},
            {"ID": 98, "Move": "Mind Reader", "Power": 0},
            {"ID": 102, "Move": "Follow Me", "Power": 0},
            {"ID": 104, "Move": "Endure", "Power": 0},
            {"ID": 106, "Move": "Scary Face", "Power": 0},
            {"ID": 112, "Move": "Uproar", "Power": 0},
            {"ID": 115, "Move": "Psych Up", "Power": 0},
            {"ID": 117, "Move": "Recover", "Power": 0},
            {"ID": 119, "Move": "Nature Power", "Power": 0},
            {"ID": 122, "Move": "Tail Whip", "Power": 0},
            {"ID": 134, "Move": "Safeguard", "Power": 0},
            {"ID": 138, "Move": "Sketch", "Power": 0},
            {"ID": 148, "Move": "Growth", "Power": 0},
            {"ID": 160, "Move": "Stockpile", "Power": 0},
            {"ID": 165, "Move": "Soft Boiled", "Power": 0},
            {"ID": 169, "Move": "Minimize", "Power": 0},
            {"ID": 171, "Move": "Supersonic", "Power": 0},
            {"ID": 173, "Move": "Moonlight", "Power": 0},
            {"ID": 181, "Move": "Swords Dance", "Power": 0},
            {"ID": 183, "Move": "Conversion", "Power": 0},
            {"ID": 184, "Move": "Conversion 2", "Power": 0},
            {"ID": 185, "Move": "Helping Hand", "Power": 0},
            {"ID": 191, "Move": "Sweet Kiss", "Power": 0},
            {"ID": 194, "Move": "Block", "Power": 0},
            {"ID": 195, "Move": "Howl", "Power": 0},
            {"ID": 217, "Move": "Growl", "Power": 0},
            {"ID": 218, "Move": "Slack Off", "Power": 0},
            {"ID": 224, "Move": "Leer", "Power": 0},
            {"ID": 225, "Move": "Wish", "Power": 0},
            {"ID": 227, "Move": "Sleep Talk", "Power": 0},
            {"ID": 229, "Move": "Assist", "Power": 0},
            {"ID": 236, "Move": "Swallow", "Power": 0},
            {"ID": 237, "Move": "Curse", "Power": 0},
            {"ID": 252, "Move": "Baton Pass", "Power": 0},
            {"ID": 254, "Move": "Splash", "Power": 0},
            {"ID": 257, "Move": "Belly Drum", "Power": 0},
            {"ID": 268, "Move": "Whirlwind", "Power": 0},
            {"ID": 273, "Move": "Flash", "Power": 0},
            {"ID": 274, "Move": "Teeter Dance", "Power": 0},
            {"ID": 281, "Move": "Glare", "Power": 0},
            {"ID": 282, "Move": "Transform", "Power": 0},
            {"ID": 284, "Move": "Roar", "Power": 0},
            {"ID": 286, "Move": "Camouflage", "Power": 0},
            {"ID": 293, "Move": "Perish Song", "Power": 0},
            {"ID": 301, "Move": "Protect", "Power": 0},
            {"ID": 302, "Move": "Defense Curl", "Power": 0},
            {"ID": 304, "Move": "Substitute", "Power": 0},
            {"ID": 315, "Move": "Foresight", "Power": 0},
            {"ID": 318, "Move": "Milk Drink", "Power": 0},
            {"ID": 326, "Move": "Attract", "Power": 0},
            {"ID": 327, "Move": "Mimic", "Power": 0},
            {"ID": 330, "Move": "Metronome", "Power": 0},
            {"ID": 337, "Move": "Recycle", "Power": 0},
            {"ID": 339, "Move": "Refresh", "Power": 0},
            {"ID": 349, "Move": "Lock On", "Power": 0},
            {"ID": 447, "Move": "Lucky Chant", "Power": 0},
            {"ID": 465, "Move": "Me First", "Power": 0},
            {"ID": 492, "Move": "Acupressure", "Power": 0},
            {"ID": 525, "Move": "Copycat", "Power": 0},
            {"ID": 534, "Move": "Captivate", "Power": 0},
        ],
    },
    "Fire": {
        "Physical": [
            {"ID": 52, "Move": "Flame Wheel", "Power": 12},
            {"ID": 149, "Move": "Sacred Fire", "Power": 50},
            {"ID": 276, "Move": "Blaze Kick", "Power": 16},
            {"ID": 292, "Move": "Fire Punch", "Power": 14},
            {"ID": 517, "Move": "Flare Blitz", "Power": 32},
            {"ID": 522, "Move": "Fire Fang", "Power": 12},
        ],
        "Special": [
            {"ID": 41, "Move": "Overheat", "Power": 20},
            {"ID": 53, "Move": "Flamethrower", "Power": 18},
            {"ID": 157, "Move": "Fire Blast", "Power": 33},
            {"ID": 230, "Move": "Heat Wave", "Power": 10},
            {"ID": 262, "Move": "Ember", "Power": 7},
            {"ID": 272, "Move": "Blast Burn", "Power": 30},
            {"ID": 278, "Move": "Eruption", "Power": 40},
            {"ID": 291, "Move": "Fire Spin", "Power": 4},
            {"ID": 519, "Move": "Lava Plume", "Power": 15},
            {"ID": 524, "Move": "Magma Storm", "Power": 55},
        ],
        "Status": [
            {"ID": 47, "Move": "Will O Wisp", "Power": 0},
            {"ID": 223, "Move": "Sunny Day", "Power": 0},
        ],
    },
    "Water": {
        "Physical": [
            {"ID": 69, "Move": "Clamp", "Power": 6},
            {"ID": 87, "Move": "Crabhammer", "Power": 18},
            {"ID": 156, "Move": "Dive", "Power": 12},
            {"ID": 158, "Move": "Waterfall", "Power": 16},
            {"ID": 432, "Move": "Aqua Jet", "Power": 4},
            {"ID": 433, "Move": "Aqua Tail", "Power": 16},
        ],
        "Special": [
            {"ID": 16, "Move": "Bubble", "Power": 4},
            {"ID": 32, "Move": "Whirlpool", "Power": 2},
            {"ID": 44, "Move": "Octazooka", "Power": 8},
            {"ID": 113, "Move": "Water Spout", "Power": 42},
            {"ID": 159, "Move": "Muddy Water", "Power": 18},
            {"ID": 219, "Move": "Surf", "Power": 30},
            {"ID": 239, "Move": "Hydro Cannon", "Power": 33},
            {"ID": 240, "Move": "Hydro Pump", "Power": 24},
            {"ID": 255, "Move": "Bubble Beam", "Power": 6},
            {"ID": 308, "Move": "Water Gun", "Power": 5},
            {"ID": 310, "Move": "Water Pulse", "Power": 12},
            {"ID": 469, "Move": "Brine", "Power": 8},
        ],
        "Status": [
            {"ID": 12, "Move": "Rain Dance", "Power": 0},
            {"ID": 70, "Move": "Withdraw", "Power": 0},
            {"ID": 307, "Move": "Water Sport", "Power": 0},
            {"ID": 434, "Move": "Aqua Ring", "Power": 0},
        ],
    },
    "Grass": {
        "Physical": [
            {"ID": 163, "Move": "Bullet Seed", "Power": 10},
            {"ID": 182, "Move": "Vine Whip", "Power": 6},
            {"ID": 221, "Move": "Needle Arm", "Power": 36},
            {"ID": 251, "Move": "Razor Leaf", "Power": 2},
            {"ID": 336, "Move": "Leaf Blade", "Power": 14},
            {"ID": 441, "Move": "Wood Hammer", "Power": 36},
            {"ID": 486, "Move": "Seed Bomb", "Power": 16},
            {"ID": 511, "Move": "Power Whip", "Power": 42},
        ],
        "Special": [
            {"ID": 76, "Move": "Giga Drain", "Power": 12},
            {"ID": 135, "Move": "Absorb", "Power": 1},
            {"ID": 151, "Move": "Solar Beam", "Power": 24},
            {"ID": 238, "Move": "Frenzy Plant", "Power": 45},
            {"ID": 253, "Move": "Petal Dance", "Power": 7},
            {"ID": 297, "Move": "Magical Leaf", "Power": 12},
            {"ID": 320, "Move": "Mega Drain", "Power": 8},
            {"ID": 443, "Move": "Energy Ball", "Power": 16},
            {"ID": 458, "Move": "Grass Knot", "Power": 1},
            {"ID": 468, "Move": "Seed Flare", "Power": 44},
            {"ID": 537, "Move": "Leaf Storm", "Power": 27},
        ],
        "Status": [
            {"ID": 15, "Move": "Aromatherapy", "Power": 0},
            {"ID": 79, "Move": "Spore", "Power": 0},
            {"ID": 84, "Move": "Grass Whistle", "Power": 0},
            {"ID": 94, "Move": "Synthesis", "Power": 0},
            {"ID": 124, "Move": "Stun Spore", "Power": 0},
            {"ID": 231, "Move": "Sleep Powder", "Power": 0},
            {"ID": 233, "Move": "Ingrain", "Power": 0},
            {"ID": 329, "Move": "Leech Seed", "Power": 0},
            {"ID": 351, "Move": "Cotton Spore", "Power": 0},
            {"ID": 504, "Move": "Worry Seed", "Power": 0},
        ],
    },
    "Electric": {
        "Physical": [
            {"ID": 65, "Move": "Thunder Punch", "Power": 6},
            {"ID": 144, "Move": "Spark", "Power": 12},
            {"ID": 354, "Move": "Volt Tackle", "Power": 24},
            {"ID": 452, "Move": "Thunder Fang", "Power": 12},
        ],
        "Special": [
            {"ID": 64, "Move": "Thunder", "Power": 45},
            {"ID": 129, "Move": "Thunderbolt", "Power": 18},
            {"ID": 188, "Move": "Thunder Shock", "Power": 1},
            {"ID": 189, "Move": "Shock Wave", "Power": 7},
            {"ID": 193, "Move": "Zap Cannon", "Power": 20},
            {"ID": 489, "Move": "Charge Beam", "Power": 9},
            {"ID": 521, "Move": "Discharge", "Power": 9},
        ],
        "Status": [
            {"ID": 128, "Move": "Charge", "Power": 0},
            {"ID": 192, "Move": "Thunder Wave", "Power": 0},
            {"ID": 493, "Move": "Magnet Rise", "Power": 0},
        ],
    },
    "Ice": {
        "Physical": [
            {"ID": 2, "Move": "Ice Ball", "Power": 1},
            {"ID": 180, "Move": "Icicle Spear", "Power": 2},
            {"ID": 344, "Move": "Ice Punch", "Power": 14},
            {"ID": 359, "Move": "Avalanche", "Power": 0},
            {"ID": 461, "Move": "Ice Fang", "Power": 10},
            {"ID": 462, "Move": "Ice Shard", "Power": 4},
            {"ID": 535, "Move": "Avalanche", "Power": 6},
        ],
        "Special": [
            {"ID": 42, "Move": "Aurora Beam", "Power": 10},
            {"ID": 97, "Move": "Icy Wind", "Power": 5},
            {"ID": 101, "Move": "Powder Snow", "Power": 4},
            {"ID": 150, "Move": "Sheer Cold", "Power": 0},
            {"ID": 270, "Move": "Blizzard", "Power": 24},
            {"ID": 345, "Move": "Ice Beam", "Power": 15},
        ],
        "Status": [
            {"ID": 14, "Move": "Hail", "Power": 0},
            {"ID": 88, "Move": "Haze", "Power": 0},
            {"ID": 130, "Move": "Mist", "Power": 0},
        ],
    },
    "Fighting": {
        "Physical": [
            {"ID": 7, "Move": "Vital Throw", "Power": 0},
            {"ID": 51, "Move": "Counter", "Power": 0},
            {"ID": 68, "Move": "Karate Chop", "Power": 10},
            {"ID": 72, "Move": "Brick Break", "Power": 14},
            {"ID": 75, "Move": "Focus Punch", "Power": 55},
            {"ID": 77, "Move": "Reversal", "Power": 2},
            {"ID": 90, "Move": "Cross Chop", "Power": 20},
            {"ID": 92, "Move": "Low Kick", "Power": 7},
            {"ID": 116, "Move": "Submission", "Power": 15},
            {"ID": 136, "Move": "Sky Uppercut", "Power": 16},
            {"ID": 170, "Move": "Seismic Toss", "Power": 0},
            {"ID": 175, "Move": "Arm Thrust", "Power": 2},
            {"ID": 204, "Move": "Jump Kick", "Power": 14},
            {"ID": 206, "Move": "High Jump Kick", "Power": 16},
            {"ID": 210, "Move": "Triple Kick", "Power": 8},
            {"ID": 222, "Move": "Double Kick", "Power": 6},
            {"ID": 243, "Move": "Superpower", "Power": 24},
            {"ID": 246, "Move": "Dynamic Punch", "Power": 10},
            {"ID": 300, "Move": "Mach Punch", "Power": 8},
            {"ID": 303, "Move": "Rolling Kick", "Power": 12},
            {"ID": 340, "Move": "Revenge", "Power": 0},
            {"ID": 358, "Move": "Revenge", "Power": 2},
            {"ID": 430, "Move": "Hammer Arm", "Power": 18},
            {"ID": 440, "Move": "Close Combat", "Power": 43},
            {"ID": 500, "Move": "Drain Punch", "Power": 13},
            {"ID": 507, "Move": "Force Palm", "Power": 12},
            {"ID": 531, "Move": "Wake Up Slap", "Power": 12},
        ],
        "Special": [
            {"ID": 454, "Move": "Focus Blast", "Power": 25},
            {"ID": 479, "Move": "Vacuum Wave", "Power": 11},
            {"ID": 508, "Move": "Aura Sphere", "Power": 16},
        ],
        "Status": [
            {"ID": 29, "Move": "Rock Smash", "Power": 0},
            {"ID": 265, "Move": "Bulk Up", "Power": 0},
            {"ID": 305, "Move": "Detect", "Power": 0},
        ],
    },
    "Poison": {
        "Physical": [
            {"ID": 198, "Move": "Poison Fang", "Power": 10},
            {"ID": 200, "Move": "Poison Sting", "Power": 3},
            {"ID": 283, "Move": "Poison Tail", "Power": 10},
            {"ID": 459, "Move": "Cross Poison", "Power": 15},
            {"ID": 485, "Move": "Gunk Shot", "Power": 22},
            {"ID": 495, "Move": "Poison Jab", "Power": 14},
        ],
        "Special": [
            {"ID": 147, "Move": "Smog", "Power": 4},
            {"ID": 279, "Move": "Sludge", "Power": 12},
            {"ID": 280, "Move": "Sludge Bomb", "Power": 18},
            {"ID": 332, "Move": "Acid", "Power": 8},
        ],
        "Status": [
            {"ID": 196, "Move": "Poison Gas", "Power": 0},
            {"ID": 197, "Move": "Toxic", "Power": 0},
            {"ID": 199, "Move": "Poison Powder", "Power": 0},
            {"ID": 202, "Move": "Acid Armor", "Power": 0},
            {"ID": 438, "Move": "Gastro Acid", "Power": 0},
            {"ID": 496, "Move": "Toxic Spikes", "Power": 0},
        ],
    },
    "Ground": {
        "Physical": [
            {"ID": 8, "Move": "Dig", "Power": 12},
            {"ID": 118, "Move": "Earthquake", "Power": 5},
            {"ID": 131, "Move": "Fissure", "Power": 0},
            {"ID": 143, "Move": "Sand Tomb", "Power": 4},
            {"ID": 285, "Move": "Bone Rush", "Power": 12},
            {"ID": 289, "Move": "Bone Club", "Power": 12},
            {"ID": 290, "Move": "Bonemerang", "Power": 10},
            {"ID": 296, "Move": "Magnitude", "Power": 0},
        ],
        "Special": [
            {"ID": 213, "Move": "Mud Slap", "Power": 4},
            {"ID": 299, "Move": "Mud Shot", "Power": 12},
            {"ID": 484, "Move": "Earth Power", "Power": 9},
            {"ID": 501, "Move": "Mud Bomb", "Power": 12},
        ],
        "Status": [
            {"ID": 142, "Move": "Sand Attack", "Power": 0},
            {"ID": 212, "Move": "Mud Sport", "Power": 0},
            {"ID": 295, "Move": "Spikes", "Power": 0},
        ],
    },
    "Flying": {
        "Physical": [
            {"ID": 100, "Move": "Sky Attack", "Power": 50},
            {"ID": 153, "Move": "Fly", "Power": 14},
            {"ID": 174, "Move": "Peck", "Power": 4},
            {"ID": 178, "Move": "Wing Attack", "Power": 6},
            {"ID": 179, "Move": "Aerial Ace", "Power": 10},
            {"ID": 205, "Move": "Bounce", "Power": 16},
            {"ID": 211, "Move": "Drill Peck", "Power": 16},
            {"ID": 490, "Move": "Pluck", "Power": 10},
            {"ID": 518, "Move": "Brave Bird", "Power": 42},
        ],
        "Special": [
            {"ID": 36, "Move": "Air Cutter", "Power": 2},
            {"ID": 57, "Move": "Gust", "Power": 4},
            {"ID": 353, "Move": "Aeroblast", "Power": 20},
            {"ID": 442, "Move": "Air Slash", "Power": 15},
            {"ID": 446, "Move": "Chatter", "Power": 10},
        ],
        "Status": [
            {"ID": 40, "Move": "Mirror Move", "Power": 0},
            {"ID": 267, "Move": "Feather Dance", "Power": 0},
            {"ID": 444, "Move": "Tailwind", "Power": 0},
            {"ID": 456, "Move": "Defog", "Power": 0},
            {"ID": 509, "Move": "Roost", "Power": 0},
        ],
    },
    "Psychic": {
        "Physical": [
            {"ID": 463, "Move": "Psycho Cut", "Power": 10},
            {"ID": 473, "Move": "Zen Headbutt", "Power": 15},
        ],
        "Special": [
            {"ID": 107, "Move": "Psybeam", "Power": 12},
            {"ID": 108, "Move": "Psywave", "Power": 0},
            {"ID": 109, "Move": "Psychic", "Power": 38},
            {"ID": 110, "Move": "Psycho Boost", "Power": 44},
            {"ID": 133, "Move": "Extrasensory", "Power": 16},
            {"ID": 234, "Move": "Confusion", "Power": 5},
            {"ID": 309, "Move": "Mist Ball", "Power": 14},
            {"ID": 316, "Move": "Mirror Coat", "Power": 0},
            {"ID": 331, "Move": "Dream Eater", "Power": 20},
            {"ID": 335, "Move": "Luster Purge", "Power": 14},
        ],
        "Status": [
            {"ID": 95, "Move": "Agility", "Power": 0},
            {"ID": 99, "Move": "Cosmic Power", "Power": 0},
            {"ID": 111, "Move": "Hypnosis", "Power": 0},
            {"ID": 137, "Move": "Skill Swap", "Power": 0},
            {"ID": 146, "Move": "Kinesis", "Power": 0},
            {"ID": 187, "Move": "Teleport", "Power": 0},
            {"ID": 209, "Move": "Trick", "Power": 0},
            {"ID": 215, "Move": "Amnesia", "Power": 0},
            {"ID": 220, "Move": "Role Play", "Power": 0},
            {"ID": 232, "Move": "Rest", "Power": 0},
            {"ID": 258, "Move": "Barrier", "Power": 0},
            {"ID": 259, "Move": "Light Screen", "Power": 0},
            {"ID": 266, "Move": "Imprison", "Power": 0},
            {"ID": 298, "Move": "Magic Coat", "Power": 0},
            {"ID": 317, "Move": "Future Sight", "Power": 0},
            {"ID": 319, "Move": "Calm Mind", "Power": 0},
            {"ID": 333, "Move": "Meditate", "Power": 0},
            {"ID": 338, "Move": "Reflect", "Power": 0},
            {"ID": 439, "Move": "Healing Wish", "Power": 0},
            {"ID": 448, "Move": "Guard Swap", "Power": 0},
            {"ID": 450, "Move": "Heal Block", "Power": 0},
            {"ID": 464, "Move": "Psycho Shift", "Power": 0},
            {"ID": 478, "Move": "Gravity", "Power": 0},
            {"ID": 499, "Move": "Trick Room", "Power": 0},
            {"ID": 506, "Move": "Heart Swap", "Power": 0},
            {"ID": 513, "Move": "Power Swap", "Power": 0},
            {"ID": 514, "Move": "Power Trick", "Power": 0},
            {"ID": 526, "Move": "Lunar Dance", "Power": 0},
            {"ID": 528, "Move": "Miracle Eye", "Power": 0},
        ],
    },
    "Bug": {
        "Physical": [
            {"ID": 80, "Move": "Leech Life", "Power": 4},
            {"ID": 164, "Move": "Twineedle", "Power": 6},
            {"ID": 306, "Move": "Pin Missile", "Power": 4},
            {"ID": 323, "Move": "Megahorn", "Power": 38},
            {"ID": 346, "Move": "Fury Cutter", "Power": 2},
            {"ID": 460, "Move": "Attack Order", "Power": 11},
            {"ID": 470, "Move": "X Scissor", "Power": 40},
            {"ID": 502, "Move": "U Turn", "Power": 14},
            {"ID": 529, "Move": "Bug Bite", "Power": 11},
        ],
        "Special": [
            {"ID": 82, "Move": "Silver Wind", "Power": 6},
            {"ID": 114, "Move": "Signal Beam", "Power": 8},
            {"ID": 530, "Move": "Bug Buzz", "Power": 16},
        ],
        "Status": [
            {"ID": 23, "Move": "String Shot", "Power": 0},
            {"ID": 86, "Move": "Spider Web", "Power": 0},
            {"ID": 288, "Move": "Tail Glow", "Power": 0},
            {"ID": 449, "Move": "Heal Order", "Power": 0},
            {"ID": 520, "Move": "Defend Order", "Power": 0},
        ],
    },
    "Rock": {
        "Physical": [
            {"ID": 28, "Move": "Rock Throw", "Power": 5},
            {"ID": 30, "Move": "Rock Slide", "Power": 14},
            {"ID": 73, "Move": "Rock Tomb", "Power": 10},
            {"ID": 105, "Move": "Rollout", "Power": 1},
            {"ID": 350, "Move": "Rock Blast", "Power": 4},
            {"ID": 453, "Move": "Rock Wrecker", "Power": 28},
            {"ID": 481, "Move": "Stone Edge", "Power": 38},
            {"ID": 533, "Move": "Head Smash", "Power": 50},
        ],
        "Special": [
            {"ID": 93, "Move": "Ancient Power", "Power": 12},
            {"ID": 512, "Move": "Power Gem", "Power": 12},
        ],
        "Status": [
            {"ID": 141, "Move": "Sandstorm", "Power": 0},
            {"ID": 480, "Move": "Stealth Rock", "Power": 0},
            {"ID": 540, "Move": "Rock Polish", "Power": 0},
        ],
    },
    "Ghost": {
        "Physical": [
            {"ID": 46, "Move": "Astonish", "Power": 6},
            {"ID": 120, "Move": "Lick", "Power": 4},
            {"ID": 126, "Move": "Shadow Punch", "Power": 6},
            {"ID": 451, "Move": "Shadow Sneak", "Power": 4},
            {"ID": 476, "Move": "Shadow Claw", "Power": 13},
            {"ID": 477, "Move": "Shadow Force", "Power": 50},
        ],
        "Special": [
            {"ID": 127, "Move": "Shadow Ball", "Power": 16},
            {"ID": 216, "Move": "Night Shade", "Power": 0},
            {"ID": 437, "Move": "Ominous Wind", "Power": 6},
        ],
        "Status": [
            {"ID": 5, "Move": "Nightmare", "Power": 0},
            {"ID": 13, "Move": "Confuse Ray", "Power": 0},
            {"ID": 35, "Move": "Spite", "Power": 0},
            {"ID": 49, "Move": "Grudge", "Power": 0},
            {"ID": 313, "Move": "Destiny Bond", "Power": 0},
        ],
    },
    "Dragon": {
        "Physical": [
            {"ID": 91, "Move": "Outrage", "Power": 18},
            {"ID": 208, "Move": "Dragon Claw", "Power": 16},
            {"ID": 498, "Move": "Dragon Rush", "Power": 40},
        ],
        "Special": [
            {"ID": 162, "Move": "Twister", "Power": 8},
            {"ID": 341, "Move": "Dragon Rage", "Power": 0},
            {"ID": 342, "Move": "Dragon Breath", "Power": 12},
            {"ID": 435, "Move": "Spacial Rend", "Power": 15},
            {"ID": 494, "Move": "Roar Of Time", "Power": 24},
            {"ID": 538, "Move": "Draco Meteor", "Power": 14},
            {"ID": 539, "Move": "Dragon Pulse", "Power": 18},
        ],
        "Status": [{"ID": 343, "Move": "Dragon Dance", "Power": 0}],
    },
    "Dark": {
        "Physical": [
            {"ID": 38, "Move": "Pursuit", "Power": 0},
            {"ID": 62, "Move": "Crunch", "Power": 16},
            {"ID": 63, "Move": "Bite", "Power": 7},
            {"ID": 167, "Move": "Faint Attack", "Power": 6},
            {"ID": 214, "Move": "Thief", "Power": 2},
            {"ID": 249, "Move": "Knock Off", "Power": 0},
            {"ID": 445, "Move": "Punishment", "Power": 1},
            {"ID": 472, "Move": "Payback", "Power": 0},
            {"ID": 488, "Move": "Assurance", "Power": 9},
            {"ID": 491, "Move": "Night Slash", "Power": 13},
            {"ID": 515, "Move": "Sucker Punch", "Power": 15},
        ],
        "Special": [
            {"ID": 436, "Move": "Dark Pulse", "Power": 16},
        ],
        "Status": [
            {"ID": 22, "Move": "Torment", "Power": 0},
            {"ID": 33, "Move": "Fake Tears", "Power": 0},
            {"ID": 43, "Move": "Memento", "Power": 0},
            {"ID": 45, "Move": "Flatter", "Power": 0},
            {"ID": 172, "Move": "Taunt", "Power": 0},
            {"ID": 269, "Move": "Beat Up", "Power": 0},
            {"ID": 334, "Move": "Snatch", "Power": 0},
            {"ID": 466, "Move": "Embargo", "Power": 0},
            {"ID": 482, "Move": "Switcheroo", "Power": 0},
            {"ID": 483, "Move": "Dark Void", "Power": 0},
            {"ID": 503, "Move": "Fling", "Power": 0},
            {"ID": 542, "Move": "Nasty Plot", "Power": 0},
        ],
    },
    "Steel": {
        "Physical": [
            {"ID": 1, "Move": "Iron Tail", "Power": 40},
            {"ID": 103, "Move": "Meteor Mash", "Power": 20},
            {"ID": 244, "Move": "Steel Wing", "Power": 35},
            {"ID": 325, "Move": "Metal Claw", "Power": 10},
            {"ID": 431, "Move": "Iron Head", "Power": 16},
            {"ID": 475, "Move": "Gyro Ball", "Power": 1},
            {"ID": 510, "Move": "Bullet Punch", "Power": 4},
            {"ID": 523, "Move": "Magnet Bomb", "Power": 12},
            {"ID": 532, "Move": "Metal Burst", "Power": 0},
        ],
        "Special": [
            {"ID": 527, "Move": "Mirror Shot", "Power": 12},
            {"ID": 536, "Move": "Flash Cannon", "Power": 15},
        ],
        "Status": [
            {"ID": 83, "Move": "Metal Sound", "Power": 0},
            {"ID": 186, "Move": "Iron Defense", "Power": 0},
            {"ID": 256, "Move": "Doom Desire", "Power": 0},
        ],
    },
    "Fairy": {
        # These Moves are unused in base game.
        "Physical": [
            # {"ID": 361, "Move": "Excavate", "Power": 2},
            # {"ID": 362, "Move": "Spin Slash", "Power": 15},
            # {"ID": 379, "Move": "Observer", "Power": 2},
            # {"ID": 398, "Move": "Famish", "Power": 2},
            # {"ID": 402, "Move": "Possess", "Power": 2},
        ],
        "Special": [
            # {"ID": "404", "Move": "[M:D1]", "Power": "2"},
            # {"ID": "411", "Move": "[M:D1]", "Power": "2"},
            # {"ID": "412", "Move": "Pierce", "Power": "2"},
            # {"ID": "413", "Move": "[M:D1]", "Power": "2"},
            # {"ID": "414", "Move": "[M:D1]", "Power": "2"},
            # {"ID": "415", "Move": "[M:D1]", "Power": "2"},
        ],
        "Status": [
            # {"ID": "416", "Move": "[M:D1]", "Power": "2"},
            # {"ID": "417", "Move": "[M:D1]", "Power": "2"},
            # {"ID": "418", "Move": "[M:D1]", "Power": "2"},
            # {"ID": "419", "Move": "[M:D1]", "Power": "2"},
            # {"ID": "420", "Move": "[M:D1]", "Power": "2"},
        ],
    },
    "None": {
        "Physical": [
            # {"ID": 355, "Move": "regular attack", "Power": 1},
            {"ID": 360, "Move": "Wide Slash", "Power": 20},
            # {"ID": 364, "Move": "Takeaway", "Power": 2},
            # {"ID": 366, "Move": "Bloop Slash", "Power": 10},
            # {"ID": 405, "Move": "projectile", "Power": 2},
            # {"ID": 547, "Move": "[M:D1]", "Power": 1},
            # {"ID": 549, "Move": "[M:D1]", "Power": 1},
            # {"ID": 550, "Move": "[M:D1]", "Power": 1},
            # {"ID": 552, "Move": "[M:D1]", "Power": 1},
            # {"ID": 553, "Move": "[M:D1]", "Power": 1},
            # {"ID": 554, "Move": "[M:D1]", "Power": 1},
            # {"ID": 555, "Move": "[M:D1]", "Power": 1},
        ],
        "Special": [
            {"ID": 324, "Move": "Hidden Power", "Power": 2},
            {"ID": 394, "Move": "Vacuum Cut", "Power": 0},
            # {"ID": 397, "Move": "Echo", "Power": 10},
            # {"ID": 543, "Move": "[M:D1]", "Power": 1},
            # {"ID": 544, "Move": "[M:D1]", "Power": 1},
            # {"ID": 545, "Move": "[M:D1]", "Power": 1},
            # {"ID": 546, "Move": "[M:D1]", "Power": 1},
            # {"ID": 548, "Move": "[M:D1]", "Power": 1},
            # {"ID": 551, "Move": "[M:D1]", "Power": 1},
            # {"ID": 557, "Move": "[M:D1]", "Power": 1},
            # {"ID": 395, "Move": "Reviver", "Power": 2},
        ],
        "Status": [
            # {"ID": 356, "Move": "is watching", "Power": 2},
            # {"ID": 363, "Move": "See-Trap", "Power": 2},
            # {"ID": 365, "Move": "Rebound", "Power": 2},
            # {"ID": 367, "Move": "Switcher", "Power": 2},
            # {"ID": 368, "Move": "Blowback", "Power": 2},
            # {"ID": 369, "Move": "Warp", "Power": 2},
            # {"ID": 370, "Move": "Transfer", "Power": 2},
            # {"ID": 371, "Move": "Slow Down", "Power": 2},
            # {"ID": 372, "Move": "Speed Boost", "Power": 2},
            # {"ID": 373, "Move": "Searchlight", "Power": 2},
            # {"ID": 374, "Move": "Petrify", "Power": 2},
            # {"ID": 375, "Move": "Stay Away", "Power": 2},
            # {"ID": 376, "Move": "Pounce", "Power": 2},
            # {"ID": 377, "Move": "Trawl", "Power": 2},
            # {"ID": 378, "Move": "Cleanse", "Power": 2},
            # {"ID": 380, "Move": "Decoy Maker", "Power": 2},
            # {"ID": 381, "Move": "Siesta", "Power": 2},
            # {"ID": 382, "Move": "Totter", "Power": 2},
            # {"ID": 383, "Move": "Two-Edge", "Power": 2},
            # {"ID": 384, "Move": "No-Move", "Power": 2},
            # {"ID": 385, "Move": "Escape", "Power": 2},
            # {"ID": 386, "Move": "Scan", "Power": 2},
            # {"ID": 387, "Move": "Power-Ears", "Power": 2},
            # {"ID": 388, "Move": "Drought", "Power": 2},
            # {"ID": 389, "Move": "Trap Buster", "Power": 2},
            # {"ID": 390, "Move": "Wild Call", "Power": 2},
            # {"ID": 391, "Move": "Invisify", "Power": 2},
            # {"ID": 392, "Move": "One-Shot", "Power": 200},
            # {"ID": 393, "Move": "HP Gauge", "Power": 2},
            # {"ID": 396, "Move": "Shocker", "Power": 2},
            # {"ID": 399, "Move": "One-Room", "Power": 2},
            # {"ID": 400, "Move": "Fill-In", "Power": 2},
            # {"ID": 401, "Move": "Trapper", "Power": 2},
            # {"ID": 403, "Move": "Itemize", "Power": 2},
            # {"ID": 406, "Move": "Hurl", "Power": 2},
            # {"ID": 407, "Move": "Mobile", "Power": 2},
            # {"ID": 408, "Move": "Item-Toss", "Power": 2},
            # {"ID": 409, "Move": "See Stairs", "Power": 2},
            # {"ID": 410, "Move": "Long Toss", "Power": 2},
            # {"ID": 412, "Move": "Pierce", "Power": 2},
            # {"ID": 421, "Move": "[M:D1]", "Power": 2},
            # {"ID": 422, "Move": "[M:D1]", "Power": 2},
            # {"ID": 423, "Move": "[M:D1]", "Power": 2},
            # {"ID": 424, "Move": "[M:D1]", "Power": 2},
            # {"ID": 425, "Move": "[M:D1]", "Power": 2},
            # {"ID": 426, "Move": "[M:D1]", "Power": 2},
            # {"ID": 427, "Move": "[M:D1]", "Power": 2},
            # {"ID": 428, "Move": "[M:D1]", "Power": 2},
            # {"ID": 429, "Move": "[M:D1]", "Power": 2},
            # {"ID": 556, "Move": "[M:D1]", "Power": 1},
            # {"ID": 558, "Move": "[M:D1]", "Power": 1},
        ],
    },
}

pokemon_signature_moves = {
    "Wide Slash": 360,
    "Vacuum Cut" : 394,
    "Crush Grip": 505,
    "Judgment": 467,
    "Sacred Fire": 149,
    "Magma Storm": 524,
    "Seed Flare": 468,
    "Aeroblast": 353,
    "Mist Ball": 309,
    "Luster Purge": 335,
    "Heart Swap": 506,
    "Lunar Dance": 526,
    "Shadow Force": 477,
    "Spacial Rend": 435,
    "Roar Of Time": 494,
    "Dark Void": 483,
    "Doom Desire": 256,
}

pokemon_hm_tm_id = {
    "Focus Punch": 75,
    "Dragon Claw": 208,
    "Water Pulse": 310,
    "Calm Mind": 319,
    "Roar": 284,
    "Toxic": 197,
    "Bulk Up": 265,
    "Bullet Seed": 163,
    "Hidden Power": 324,
    "Taunt": 172,
    "Ice Beam": 345,
    "Blizzard": 270,
    "Hyper Beam": 242,
    "Light Screen": 259,
    "Protect": 301,
    "Giga Drain": 76,
    "Safeguard": 134,
    "Frustration": 328,
    "Solar Beam": 151,
    "Iron Tail": 1,
    "Thunderbolt": 129,
    "Thunder": 64,
    "Earthquake": 118,
    "Return": 48,
    "Dig": 8,
    "Psychic": 109,
    "Shadow Ball": 127,
    "Brick Break": 72,
    "Reflect": 338,
    "Shock Wave": 189,
    "Flamethrower": 53,
    "Sludge Bomb": 280,
    "Fire Blast": 157,
    "Aerial Ace": 179,
    "Torment": 22,
    "Facade": 67,
    "Secret Power": 263,
    "Rest": 232,
    "Attract": 326,
    "Thief": 214,
    "Steel Wing": 244,
    "Skill Swap": 137,
    "Overheat": 41,
    "Roost": 509,
    "Focus Blast": 454,
    "Energy Ball": 443,
    "False Swipe": 314,
    "Brine": 469,
    "Fling": 503,
    "Charge Beam": 489,
    "Endure": 104,
    "Dragon Pulse": 539,
    "Drain Punch": 500,
    "Will O Wisp": 47,
    "Silver Wind": 82,
    "Embargo": 466,
    "Explosion": 155,
    "Shadow Claw": 476,
    "Payback": 472,
    "Recycle": 337,
    "Giga Impact": 455,
    "Rock Polish": 540,
    "Flash": 273,
    "Stone Edge": 481,
    "Avalanche": 535,
    "Thunder Wave": 192,
    "Gyro Ball": 475,
    "Swords Dance": 181,
    "Stealth Rock": 480,
    "Psych Up": 115,
    "Captivate": 534,
    "Dark Pulse": 436,
    "Rock Slide": 30,
    "X Scissor": 470,
    "Sleep Talk": 227,
    "Natural Gift": 471,
    "Poison Jab": 495,
    "Dream Eater": 331,
    "Grass Knot": 458,
    "Swagger": 24,
    "Pluck": 490,
    "U turn": 502,
    "Substitute": 304,
    "Flash Cannon": 536,
    "Trick Room": 499,
    "Dive": 156,
    "Vacuum Cut": 394,
    "Wide Slash": 360,
    "Cut": 18,
    "Fly": 153,
    "Surf": 219,
    "Strength": 50,
    "Defog": 456,
    "Rock Smash": 29,
    "Waterfall": 158,
    "Rock Climb": 541,
}

pokemon_types_id = {
    # "None": 0,
    "Normal": 1,
    "Fire": 2,
    "Water": 3,
    "Grass": 4,
    "Electric": 5,
    "Ice": 6,
    "Fighting": 7,
    "Poison": 8,
    "Ground": 9,
    "Flying": 10,
    "Psychic": 11,
    "Bug": 12,
    "Rock": 13,
    "Ghost": 14,
    "Dragon": 15,
    "Dark": 16,
    "Steel": 17,
    "Fairy": 18,
}

pokemon_abilities_id = {
    # 'Unknown': 0,
    'Stench': 1,
    'Thick Fat': 2,
    'Rain Dish': 3,
    'Drizzle': 4,
    'Arena Trap': 5,
    'Intimidate': 6,
    'Rock Head': 7,
    'Air Lock': 8,
    'Hyper Cutter': 9,
    'Shadow Tag': 10,
    'Speed Boost': 11,
    'Battle Armor': 12,
    'Sturdy': 13,
    'Suction Cups': 14,
    'Clear Body': 15,
    'Torrent': 16,
    'Guts': 17,
    'Rough Skin': 18,
    'Shell Armor': 19,
    'Natural Cure': 20,
    'Damp': 21,
    'Limber': 22,
    'Magnet Pull': 23,
    'White Smoke': 24,
    'Synchronize': 25,
    'Overgrow': 26,
    'Swift Swim': 27,
    'Sand Stream': 28,
    'Sand Veil': 29,
    'Keen Eye': 30,
    'Inner Focus': 31,
    'Static': 32,
    'Shed Skin': 33,
    'Huge Power': 34,
    'Volt Absorb': 35,
    'Water Absorb': 36,
    'Forecast': 37,
    'Serene Grace': 38,
    'Poison Point': 39,
    'Trace': 40,
    'Oblivious': 41,
    'Truant': 42,
    'Run Away': 43,
    'Sticky Hold': 44,
    'Could Nine': 45,
    'Illuminate': 46,
    'Early Bird': 47,
    'Hustle': 48,
    'Drought': 49,
    'Lightning Rod': 50,
    'Compound Eyes': 51,
    'Marvel Scale': 52,
    'Wonder Guard': 53,
    'Insomnia': 54,
    'Levitate': 55,
    'Plus': 56,
    'Pressure': 57,
    'Liquid Ooze': 58,
    'Color Change': 59,
    'Soundproof': 60,
    'Effect Spore': 61,
    'Flame Body': 62,
    'Minus': 63,
    'Own Tempo': 64,
    'Magma Armor': 65,
    'Water Veil': 66,
    'Swarm': 67,
    'Cute Charm': 68,
    'Immunity': 69,
    'Blaze': 70,
    'Pickup': 71,
    'Flash Fire': 72,
    'Vital Spirit': 73,
    'Chlorophyll': 74,
    'Pure Power': 75,
    'Shield Dust': 76,
    'Ice Body': 77,
    'Stall': 78,
    'Anger Point': 79,
    'Tinted Lens': 80,
    'Hydration': 81,
    'Frisk': 82,
    'Mold Breaker': 83,
    'Unburden': 84,
    'Dry Skin': 85,
    'Anticipation': 86,
    'Scrappy': 87,
    'Super Luck': 88,
    'Gluttony': 89,
    'Solar Power': 90,
    'Skill Link': 91,
    'Reckless': 92,
    'Sniper': 93,
    'Slow Start': 94,
    'Heatproof': 95,
    'Download': 96,
    'Simple': 97,
    'Tangled Feet': 98,
    'Adaptability': 99,
    'Technician': 100,
    'Iron Fist': 101,
    'Motor Drive': 102,
    'Unaware': 103,
    'Rivalry': 104,
    'Bad Dreams': 105,
    'No Guard': 106,
    'Normalize': 107,
    'Solid Rock': 108,
    'Quick Feet': 109,
    'Filter': 110,
    'Klutz': 111,
    'Steadfast': 112,
    'Flower Gift': 113,
    'Poison Heal': 114,
    'Magic Guard': 115,
    # "Invalid ('$$$')": 116,
    'Honey Gather': 117,
    'Aftermath': 118,
    'Snow Cloak': 119,
    'Snow Warning': 120,
    'Forewarn': 121,
    'Storm Drain': 122,
    'Leaf Guard': 123
}

pokemon_signature_abilities = {
  'Flower Gift': 113,
  'Bad Dreams': 105,
  'Slow Start': 94,
  'Wonder Guard': 53,
  'Forecast': 37,
}

movement_types = {
    "Flying": 2,
    "Ghost": 3,
    "Fire": 4,
    "Water": 5,
    "Levitate": 2,
}

weight_ranges = {
    (-float('inf'), 299): 153,
    (300, 399): 179,
    (400, 499): 204,
    (500, 599): 230,
    (600, 699): 256,
    (700, 799): 281,
    (800, 899): 307,
    (900, 999): 332,
    (1000, float('inf')): 358
}

recruitrate_ranges = {
    (-float('inf'), 249): 300,
    (250, 299): 200,
    (300, 339): 164,
    (340, 347): 136,
    (348, 355): 128,
    (356, 363): 112,
    (364, 371): 110,
    (372, 379): 100,
    (380, 387): 90,
    (388, 395): 82,
    (396, 403): 78,
    (404, 411): 69,
    (412, 419): 68,
    (420, 427): 67,
    (428, 435): 64,
    (436, 443): 60,
    (444, 451): 56,
    (452, 459): 55,
    (460, 467): 52,
    (468, 475): 51,
    (476, 483): 50,
    (484, 491): 45,
    (492, 499): 40,
    (500, 507): 39,
    (508, 515): 35,
    (516, 523): 30,
    (524, 531): 25,
    (532, 539): 20,
    (540, 547): 15,
    (548, 555): 10,
    (556, 563): 7,
    (564, 571): 5,
    (572, 579): 1,
    (580, 587): 0,
    (588, 600): -45,
    (601, 650): -100,
    (651, 699): -120,
    (700, float('inf')): -220
}

size_ranges = {
    (-float("inf"), 1): 8,
    (2, 4): 9,
    (5, 7): 10,
    (8, 9): 11,
    (10, 12): 12,
    (13, 15): 13,
    (16, 17): 14,
    (18, 20): 15,
    (21, 23): 16,
    (24, 26): 17,
    (27, 28): 18,
    (29, 31): 19,
    (32, 34): 20,
    (35, 36): 21,
    (37, 39): 22,
    (40, 42): 23,
    (43, 44): 24,
    (45, 47): 25,
    (48, 50): 26,
    (51, 53): 27,
    (54, 55): 28,
    (56, 58): 29,
    (59, 61): 30,
    (62, 63): 31,
    (64, 66): 32,
    (67, 69): 33,
    (70, 71): 34,
    (72, 74): 35,
    (75, 77): 36,
    (78, 80): 37,
    (81, 82): 38,
    (83, 85): 39,
    (86, 88): 40,
    (89, 90): 41,
    (91, 93): 42,
    (94, 96): 43,
    (97, 99): 44,
    (100, 101): 45,
    (102, 104): 46,
    (105, 107): 47,
    (108, 109): 48,
    (110, 112): 49,
    (113, 115): 50,
    (116, 117): 51,
    (118, 120): 52,
    (121, 123): 53,
    (124, 126): 54,
    (127, 128): 55,
    (129, 131): 56,
    (132, 134): 57,
    (135, 136): 58,
    (137, 139): 59,
    (140, 142): 60,
    (143, 144): 61,
    (145, 147): 63,
    (148, 150): 64,
    (151, 153): 65,
    (154, 155): 68,
    (156, 158): 69,
    (159, 161): 72,
    (162, 163): 76,
    (164, 166): 86,
    (167, 169): 87,
    (170, 171): 92,
    (172, 174): 94,
    (175, 177): 99,
    (178, 180): 107,
    (181, 182): 115,
    (183, 185): 116,
    (186, 188): 119,
    (189, 190): 122,
    (191, 193): 124,
    (194, 196): 156,
    (197, 199): 167,
    (200, float("inf")): 225,
}

shadow_ranges = {
    (-float('inf'), 99): 0,
    (100, 199): 1,
    (200, float('inf')): 2,
}

body_size_ranges = {
    (-float('inf'), 99): 1,
    (100, 199): 2,
    (200, float('inf')): 4,
}

personality_array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 25]

pokemon_iq_array = [0, 1, 2, 3, 4, 5, 6, 7]

asleepchance_array= [0, 5, 8, 10, 12, 15, 20]

no_drop_rate_array = [750, 800]

normal_drop_rate_array = [15, 21]

type_one_drop_rate_array = [27, 28, 30]

type_two_drop_rate_array = [10, 27, 28]

starter_base_stats = {
    "HP": (20, 25),
    "Other": (2, 5),
    "Total": (30, 40),
}

normal_base_stats = {
    "HP": (30, 40),
    "Other": (5, 15),
    "Total": (50, 70),    
}

legendary_base_stats = {
    "HP": (25, 55),
    "Other": (15, 30),
    "Total": (80, 140),
}

